### ISSUE TITLE
Cannot sign in

### ISSUE THREAD

**Issue by Gisonrg** [fanshicomic/Adherence-Activity#1]
RT

**Comment by fanshicomic** [comment]
→_→我还在搞
吃什么💩

Jiang Sheng notifications@github.com于2015年5月12日星期二写道：

> RT
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/fanshicomic/Adherence-Activity/issues/1.

## 

Regards,
Fanshi

**Comment by Gisonrg** [comment]
help needed pls！
